package com.llb.test.im.server.entity;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.online_status
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private Integer onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private Date lastLoginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_logout_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private Date lastLogoutAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.created_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.online_status
     *
     * @return the value of account.online_status
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.online_status
     *
     * @param onlineStatus the value for account.online_status
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login_at
     *
     * @return the value of account.last_login_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public Date getLastLoginAt() {
        return lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login_at
     *
     * @param lastLoginAt the value for account.last_login_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setLastLoginAt(Date lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_logout_at
     *
     * @return the value of account.last_logout_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public Date getLastLogoutAt() {
        return lastLogoutAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_logout_at
     *
     * @param lastLogoutAt the value for account.last_logout_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setLastLogoutAt(Date lastLogoutAt) {
        this.lastLogoutAt = lastLogoutAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.created_at
     *
     * @return the value of account.created_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.created_at
     *
     * @param createdAt the value for account.created_at
     *
     * @mbg.generated Thu Sep 19 23:01:00 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}